### ISSUE TITLE
Pcap fais to run because of different NODE_MODULE_VERSION

### ISSUE THREAD

**Issue by critocrito** [samatt/herbivore#29]
I try to run herbivore on my Linux system. When running `npm run dev` I get the following error message in the developer tools console:

```
Uncaught Error: The module '/home/crito/src/herbivore/app/node_modules/pcap/build/Release/pcap_binding.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 57. This version of Node.js requires
NODE_MODULE_VERSION 53. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or`npm install`).
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:173:20)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/crito/src/herbivore/app/node_modules/pcap/pcap.js:3:21)
    at Object.<anonymous> (/home/crito/src/herbivore/app/node_modules/pcap/pcap.js:130:3)
```

I'm using Archlinux and `libpcacp` is installed. I tried it with NodeJS 8.2.1 and 7.7.4. Also looking [here](https://nodejs.org/en/download/releases/), I don't really know which version of NodeJS has `NODE_MODULE_VERSION` 53. What version of NodeJS do you know to work?

**Comment by samatt** [comment]
https://stackoverflow.com/questions/42616008/node-module-version-conflict-when-installing-modules-for-electron

**Comment by kaganjd** [comment]
#31 should fix this! You'd pull the latest and run `npm install` then `npm run rebuild`. If it doesn't, let me know and I'll reopen.

**Comment by critocrito** [comment]
I had to run `npm run rebuild` and that did the trick for me. Thanks.
